>>> %Run Window.py
Exception in thread Thread-1 (loop):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/Downloads/ilyass-main/PythonProject/Window.py", line 77, in loop
    if status == sensor.DHTLIB_OK:
                 ^^^^^^^^^^^^^^^^
AttributeError: 'DHT' object has no attribute 'DHTLIB_OK'
